### PR TITLE
Added Another set of JSON files(61)

### PR DESCRIPTION
**Pull request by Msgtfrank**
Last of my batch of JSON files. Will be happy to help fix things if anyone finds any errors!

### CODE REVIEW

**Comment by dnoliver** [comment]
@Msgtfrank at least json lint found no issues in your json files

**Comment by malikabhi05** [comment]
@Msgtfrank please add your signoff to the commits in this PR

**Comment by Msgtfrank** [comment]
@malikabhi05 I believe that should have done it. Still kinda new to github, sorry.

**Comment by malikabhi05** [comment]
Merged, Thanks!!

**Pull request closed without merging**
