### PR TITLE
grovescam: Initial implementation

### PR DESCRIPTION
**Pull request by Jon-ICS**
This module was developed on the Grove Serial Camera.  It connects to
the UART and runs at 115200 baud.  It was developed based on the Seeed
Studio Arduino sketch, as there appears to be no protocol
documentation available.

Signed-off-by: Jon Trulson <jtrulson@ics.com>

### CODE REVIEW

**Comment by Propanu** [comment]
Thanks! Merged here: 4390c30be80de94919eb13741bbfc46456e4b6f7.

**Comment by victorsosaio** [comment]
Based on this thread, I'm not sure how this module passed the tests. 

https://communities.intel.com/message/341456#341456

I'm facing the same problems and the thread seems to be very concise in that the Grove Serial Camera is not supported in Edison. Could you shed some light here, please? Maybe starting at how you tested it (if by any chance recall it)?

Thanks!

**Comment by jontrulson** [comment]
This is a TTL level device.  It was tested with the Galileo 2 and Intel Edison w/ arduino breakout.  It worked fine on the G2.  On the edison it failed to read any data.  However, when I connected a DSO to the RX/TX lines it then was able to read data (from my notes at the time). 

That was a couple years ago.  The dmesg output you posted in that thread indicates a kernel driver problem.  I did not see kernel problems at the time.

**Comment by sosahvictor** [comment]
Thank you, @jontrulson and @Propanu. I'll give it a try to your suggestions. In the meantime I opened issue #545.

**Pull request closed without merging**
