### PR TITLE
cmake: Move find package early to avoid unsetting cross compile flags…

### PR DESCRIPTION
**Pull request by arfoll**
… in configure stage

Signed-off-by: Brendan Le Foll <brendan.le.foll@intel.com>

### CODE REVIEW

**Comment by arfoll** [comment]
With the following fix CFLAGS are appended so this stops this issue.

**Comment by pylbert** [comment]
This should have been fixed here: https://github.com/intel-iot-devkit/upm/commit/cdc33ceb9fd592e82c1eb940dbac5cb0fbfeded2#diff-af3b638bc2a3e6c650974192a53c7291R89 

Let me know if this is not the case.

**Comment by Propanu** [comment]
Is this confirmed fixed?

**Comment by pylbert** [comment]
Fixed in cdc33ceb9fd592e82c1eb940dbac5cb0fbfeded2

**Pull request closed without merging**
