### PR TITLE
hx711: Initial implementation #139

### PR DESCRIPTION
**Pull request by rafaneri**
An initial implementation for [hx711](http://www.dfrobot.com/image/data/SEN0160/hx711_english.pdf) 24bit adc for scales, inspired on https://github.com/bogde/HX711.

### CODE REVIEW

**Comment by Propanu** [comment]
Since this is all part of the initial implementation for this sensor, I plan to squash everything in a single commit. However I need your help with 2 things:
* Please add your e-mail address next to your name in the code files
* Signoff at least one of your commits (you can use `--signoff` in the `git commit` line to achieve that)

Thank you for partaking in our effort!

**Comment by rafaneri** [comment]
Ok, done!

**Comment by Propanu** [comment]
Thanks! I've added your code to the library in df302ff5db962d8be94acbc6371b3999f331b053.

**Comment by rafaneri** [comment]
Thanks! It's a pleasure to collaborate with the project!
Can you close the Issue #139 ?

**Pull request closed without merging**
