### PR TITLE
adis16448: initial implementation

### PR DESCRIPTION
**Pull request by juchong**
Added support for the ADIS16448 IMU. The IMU is communicating via SPI using mraa and a level translator. C++ and Java code has been tested. Example code is included for both languages.

### CODE REVIEW

**Comment by jrvandr** [comment]
Thank you!
Please add a signoff mentioned in the below link and we'll get it merged in.
http://iotdk.intel.com/docs/master/upm/contributions.html

**Comment by juchong** [comment]
Signed-off-by: Juan J Chong <juanjchong@gmail.com>

**Comment by jrvandr** [comment]
I just noticed the lgpl license, is there a specific reason the code needs to be lgpl?  Would it be possible for you to re-submit it under the MIT license?

**Comment by juchong** [comment]
Definitely! Sorry about that, I just kind of picked a license. Let me get everything updated!

**Comment by jrvandr** [comment]
No problem at all.
That's great, thank you very much!
I just figured I'd check with you since MIT is the preferred license for this project.

**Comment by juchong** [comment]
Good to go! Let me know if you find any other issues. I also went ahead and updated the description a bit.

**Comment by jrvandr** [comment]
It looks like there is still lgpl in the header comments.  I'm seeing the following lines in the files:

 //
 // This example is free software. You can redistribute it and/or modify it
 // under the terms of the GNU Lesser Public License as published by the Free Software
 // Foundation, either version 3 of the License, or any later version.
 //

**Comment by jrvandr** [comment]
Can you also please elaborate on the line that was in the original commit:
-// This library is based on the ADIS16480 library written by Daniel Tatum.
Was this code licensed previously? and if so, under which license.  If the original license is different than the one the current code is being submitted under, a signoff of the original author would be needed to change the license.

**Comment by juchong** [comment]
Are you sure you're looking at the most recent commit? I don't see any of the old licenses in my fork. 

The library was originally written for an ADIS16480 device and an Arduino. The ADIS16480 uses pages and supports many other features that the ADIS16448 is incapable of using. At this point, the only reminiscence of the original author's code is the .h structure.

**Comment by jrvandr** [comment]
Thanks for clarifying.
The Developer's Certificate of Origin 1.1(http://iotdk.intel.com/docs/master/upm/contributions.html) describes details that apply to situations like these.  With your signoff, we know you've reviewed these for your submission.  Thank you for giving it your attention :)


The latest commit(3b376d1c502080675a85c7bebfe9053cd42259d5) show the comment block and doesn't mention MIT:
//
// This example is free software. You can redistribute it and/or modify it
// under the terms of the GNU Lesser Public License as published by the Free Software
// Foundation, either version 3 of the License, or any later version.
//
Try clicking the commit tab on this page and then clicking each commit.  The above text has not been marked for removal in the most recent commit.  Perhaps you have a commit to add with some additional changes?

**Comment by juchong** [comment]
There we go. The latest commit should be available! I hadn't verified another e-mail I used to submit it.

**Comment by jrvandr** [comment]
The submission shows 3b376d1c502080675a85c7bebfe9053cd42259d5 as the latest commit and contains the following LGPL license text:
//
// This example is free software. You can redistribute it and/or modify it
// under the terms of the GNU Lesser Public License as published by the Free Software
// Foundation, either version 3 of the License, or any later version.
//

Please re-submit your code licensed under MIT and remove any previous LGPL license text from the comments.  Thanks!

**Comment by juchong** [comment]
I'm not really sure where you're seeing the comments. The latest update https://github.com/juchong/upm/commit/3b376d1c502080675a85c7bebfe9053cd42259d5 shows the MIT license. What file are you seeing this in?

**Comment by jrvandr** [comment]
3b376d
Attached is the image of what I'm seeing.

**Comment by juchong** [comment]
There we go. Sorry about that! I guess in copying and pasting I left that paragraph in the comments.

**Comment by jrvandr** [comment]
Great, thank you!  No problem, it's quite alright :)

One last thing, it looks like the top few lines of the license file was missed in the files you've submitted.  Please add the following two lines to your files. I've included the MIT license link for reference and also included a link to an example file already in our repository:


The MIT License (MIT)

Copyright (c) <year> <copyright holders>



http://opensource.org/licenses/MIT

https://github.com/intel-iot-devkit/upm/blob/master/src/lcd/lcm1602.h

**Comment by juchong** [comment]
There we go!

**Comment by Propanu** [comment]
Please include your full e-mail address in the author line inside the brackets like so:
`Author: Juan Jose Chong <juanjchong@gmail.com>`
Then commit your changes with the following git command:
`git commit -a -s -m "adis16448: initial implementation"`
This will sign-off your commit and we'll be able to squash & merge it with our code base.

Thanks!

**Comment by jrvandr** [comment]
Thank you very much Juan, your contribution to UPM is greatly appreciated!  Your module has been merged in to our repository and the pull request is being closed.  In response to your comment during submission process, we've updated our web page to help clarify guidelines and requirements for contributing modules.  https://github.com/intel-iot-devkit/upm/blob/master/docs/contributions.md

**Pull request closed without merging**
