### PR TITLE
Drivers for Grove Circular LED and UltraSonic Ranger modules

### PR DESCRIPTION
**Pull request by arcatdmz**
I implemented drivers for [Grove Ultrasonic Ranger](http://www.seeedstudio.com/wiki/Grove_-_Ultrasonic_Ranger) (pretty similar to but different from HC-SR04) and [Grove Circular LED](http://www.seeedstudio.com/wiki/Grove_-_Circular_LED).
The code is tested on my Intel Edison + Arduino Breakout Board + Grove Shield v2 with these software/library:
```bash
root@edison:~# cat /etc/version
weekly-120
root@edison:~# opkg info libmraa0 | grep Version
Version: 0.6.1
```

Let me know if missed anything :)

### CODE REVIEW

**Comment by Propanu** [comment]
Before we can merge your new sensors, you'll need to perform some minor changes:
* We use the following naming convention for commits `<libname>: description`
* Commits must be signed, you can achieve that by adding `-s` in your `git commit` line
* Your name and e-mail must be included in every code file that you add (cxx, h, js, py). If your work uses existing UPM code but significant changes have been made, you don't have to mention the previous author again. You can however list the module name of the original code in the license (e.g. Based on lib-X by Y).

All these changes can be achieved easily by amending your commits and force pushing the branch again. More details in [here] (../blob/master/docs/contributions.md) and [here] (../blob/master/docs/documentation.md).
Let us know if you need any help and thank you for your contribution!!

**Comment by arcatdmz** [comment]
Thanks for your detailed instruction! Let me handle this...

**Comment by Propanu** [comment]
No worries, let us know when your code is ready!

**Comment by arcatdmz** [comment]
It seems like my pull request is already partly merged [here](https://github.com/intel-iot-devkit/upm/tree/master/src/grovecircularled), so let me close this pull request.

For the rest of the code for [the ultrasonic ranger](http://www.seeedstudio.com/wiki/Grove_-_Ultrasonic_Ranger), let me create another pull request that follows the contributor's convention :)

**Comment by Propanu** [comment]
That would be great, thanks a lot!!

**Pull request closed without merging**
