### PR TITLE
Changes for nodejs 4.1.1

### PR DESCRIPTION
**Pull request by xbolshe**
Changes for nodejs 4.1.1

### CODE REVIEW

**Comment by arfoll** [comment]
Recommend waiting for https://github.com/intel-iot-devkit/mraa/pull/297 to be resolved before merging.

**Comment by xbolshe** [comment]
About changes:
1. c++11 is required to be enable
2. ds1307 example works without problem
3. lsm303 does not work. And I see several problems here. One of them is related with SWIG 3.0.7 code generation.

**Comment by Propanu** [comment]
@xbolshe are you saying the the output type maps don't work correctly anymore with SWIG 3.0.7? That would affect *A LOT* of other sensors too. Can you also please open this an an issue so that I can close this and keep track of it separately?

Thanks!

**Comment by xbolshe** [comment]
See https://github.com/intel-iot-devkit/upm/issues/288

**Comment by xbolshe** [comment]
See https://github.com/intel-iot-devkit/upm/pull/289

**Comment by Propanu** [comment]
Can you please resubmit this patch? It doesn't seem to be available on your master anymore.

**Comment by xbolshe** [comment]
See https://github.com/intel-iot-devkit/upm/pull/309

**Comment by Propanu** [comment]
Merged the resubmitted patch. Thanks!

**Pull request closed without merging**
