### PR TITLE
ms5611: Initial implementation.

### PR DESCRIPTION
**Pull request by whbruce**
Signed-off-by: Henry Bruce <henry.bruce@intel.com>

### CODE REVIEW

**Comment by whbruce** [comment]
I need to resolve some cosmetic issues with commit. Please don't merge until I give the go-ahead.

**Comment by whbruce** [comment]
OK, should be good to go now.

**Comment by whbruce** [comment]
Argh. I'm an idiot. Please hold.

**Comment by whbruce** [comment]
OK. I double checked this time and it should be OK.

**Comment by Propanu** [comment]
This was merged, thank you @whbruce!

**Pull request closed without merging**
