### PR TITLE
smartdrive: fixed x and y

### PR DESCRIPTION
**Pull request by neuberfran**
Signed-off-by: neuberfran <neuberfran@bol.com.br>

### CODE REVIEW

**Comment by neuberfran** [comment]
Please, tell me why files smartdrive.cxx and smartdrive.hpp in upm sensor not have new changes yet

**Comment by Propanu** [comment]
Does this code work correctly for your setup? The only significant changes I see are [this](https://github.com/intel-iot-devkit/upm/pull/554/files#diff-270a402cdeae1f945260be6088d61817R187) and [this](https://github.com/intel-iot-devkit/upm/pull/554/files#diff-270a402cdeae1f945260be6088d61817R191), pointing to your motors being swapped compared to the image on the first page of the [user manual](http://www.mindsensors.com/index.php?controller=attachment&id_attachment=121). This should be fixed in your application code and not in the driver.

**Comment by neuberfran** [comment]
You are wrong. I tested atual code in two intel edison boards with yocto/node.js scripts (my) and not worked correctly. With my code (smartdrive.cxx and smartdrive.hpp) My scripts worked. Please change.

**Comment by Propanu** [comment]
Can you paste the node.js script you are using with the library here?

There are several issues with your updated code that did not pass our review, namely:
- Commit message needs to be updated, I used "x" and "y" as placeholders for actual description of changes.
- Author should not be removed and replaced, it's fine if you want to add yourself to the list though.
- There are a couple of instances where you replace a symbol with the exact same numerical value in the .hpp file, e.g. `CMD_S == 0x53`. This is not needed.
- In some places you use a hard-coded '5' when calling `writeArray()`, but the array is larger than 5 bytes, throwing away the rest of the command.
- You shouldn't make repeated calls to `i2c.address` since it's saved in the context (see #547).
- Formatting/indentation should match existing code (you have extra spaces, tabs, etc.)

**Comment by neuberfran** [comment]
var smart = require('jsupm_smartdrive');
var smarttest = smart.SmartDrive;
var smarttest = new smart.SmartDrive(0);
var teste = smarttest.GetBattVoltage();

setTimeout(function(){
    smarttest.Run_Seconds(0x02,0x00, 90, 70, true, 0x01 );

    console.log(teste);
    setInterval(function(){
           smarttest.StopMotor(0x02,0x02);
    }, 4000);
}, 4000);

**and**

ar smart = require('jsupm_smartdrive');
var smarttest = new smart.SmartDrive(0);
var teste = smarttest.GetBattVoltage();

setTimeout(function(){
    smarttest.Run_Seconds(0x03,0x00, 90, 70, true, 0x01 );

    console.log(teste);
    setInterval(function(){
           smarttest.StopMotor(0x03,0x02);
    }, 4000);
}, 4000);

**I do not see problems in leaving the author's name**
Oussema Harbi <oussema.elharbi@gmail.com>

**Comment by Propanu** [comment]
With your code changes and 1st test script, which motor turns M1 or M2? Refer to the picture on the first page [here](http://www.mindsensors.com/index.php?controller=attachment&id_attachment=121). It may be possible that the firmware of the motor controller has them backwards.

I'm assuming with the 2nd test script both of them turn as expected?

**Comment by neuberfran** [comment]
With the first script run motor 2 (0x02). But if  run a second script Immediately after the first, run  only motor 2 and stop after 2 seconds. After that, yes, the two motors. I change de smarttest do smarttestb in first script but not solved. I stay usaing my smartdrive.cxx and my smartdrive.hpp codes in this casa. The smartdrive.cxx and smartdrive.hpp of the upm sensor I try i last month and not worked

**Comment by neuberfran** [comment]
Today, 22:00 PM I stay trying use atual smartdrive atual sensor, and I have issues:

First I do this: **cmake ..// make smartdrive // make install** 

tela2doc

After I try run scripts above and code of the /usr/examples/c++ with ID_1  because this: (https://drive.google.com/file/d/0B9gPdWq4OH-XaUpfekFyLXdXeDQ/view?usp=sharing)

**_### But motors never run_** with _BOTH option the light red in smartdrive physic ON
tela4c

**Comment by neuberfran** [comment]
The code that is currently in github is definitely wrong. Look at this:

image

We need to correct

**Comment by Propanu** [comment]
@neuberfran, the [python library provided by openelectrons](https://pypi.python.org/pypi/SmartDrive/1.0) matches the current code in UPM:
```py
            if ( (motor_number & 0x01) != 0 ):
                array = [speed, duration, 0, ctrl]
                self.writeArray( self.SmartDrive_SPEED_M1, array) 
            if ( (motor_number & 0x02) != 0 ) :
                array = [speed, duration, 0, ctrl]
                self.writeArray( self.SmartDrive_SPEED_M2, array)
```
What may be happening in your case, is that you build the new library after it was patched, and install it under `/usr/local/lib` on your Edison. However, the old library is still under `/usr/lib` and that's the one your example links against. This is further hinted to from the error messages thrown by dlopen. Can you check the version on that and confirm it's 1.0 or newer?

Alternatively, run
```
opkg update
opkg upgrade mraa upm
```
On your Edison and it should grab the latest for you. Then try your test script again.

**Comment by neuberfran** [comment]
https://github.com/intel-iot-devkit/upm/pull/557

**Comment by neuberfran** [comment]
Driver funcionou no Android Things DP3/intel edison/jcenter/gradle

**Pull request closed without merging**
