### PR TITLE
Pull enc03r

### PR DESCRIPTION
**Pull request by Jon-ICS**
This adds support for the ENC03R Single Axis Analog Gyro.

### CODE REVIEW

**Comment by arfoll** [comment]
Two reverts? And 5 merges? You may want to look into rebase.... For this and all the other PRs.

**Comment by Jon-ICS** [comment]
Sorry about that.  I have looked into rebase, but it's not clear how to use it to fix those problems.  Do all of these PR's need to be closed and I should just start over?

**Comment by rwaldron** [comment]
Assuming you have `git remote add upstream https://github.com/intel-iot-devkit/upm.git`

From your `pull_enc03r` branch: 

`git pull --rebase upstream master`

**Comment by Jon-ICS** [comment]
Thanks, I did have upstream set up.  I did as you suggested - this got rid of the merges.  I then did an interactive rebase to remove the two commits and their reverts and did a push -f.  This looks way better, though I'm not fond of push -f...

Originally, another developer had accidentally committed his changes to master, and I simply reverted them.  I think this was a mistake, as it affected all branches afterward.

Let me know if the current state of this branch is acceptable for meging with upstream, and I will then go fix up the others already submitted and any that are forthcoming.

Thanks for the hint rwaldron!

**Comment by arfoll** [comment]
Well I haven't looked at the code but this looks much much better. Nothing wrong with push --force as long as you're not the upstream, especially in feature branches.

**Comment by Jon-ICS** [comment]
Ok, thanks!  I will go fix up the other 4 in the same way.

Sorry for the mess.

**Comment by sknepper** [comment]
Merged in.  Thanks so much!

**Pull request closed without merging**
