### PR TITLE
grovedryreedrelay: Initial implementation

### PR DESCRIPTION
**Pull request by Jon-ICS**
Signed-off-by: Jon Trulson <jtrulson@ics.com>
Signed-off-by: Zion Orent <zorent@ics.com>

### CODE REVIEW

**Comment by jrvandr** [comment]
Looking at the other relay sample we have to see about any streamlining that can be done.  work in progress.

**Comment by Jon-ICS** [comment]
On 01/19/2015 01:50 PM, jrvandr wrote:
>
> Looking at the other relay sample we have to see about any 
> streamlining that can be done. work in progress.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/intel-iot-devkit/upm/pull/46#issuecomment-70558177>.
>

Yes, I noticed that a generic grove relay driver was recently merged.  
This could probably be drive the reed relay fine...

-- 
Jon Trulson
Integrated Computer Solutions
www.ics.com

**Comment by Propanu** [comment]
@jrvandr can we salvage any contributions from this PR (e.g. examples)?

**Comment by Propanu** [comment]
Will use existing code as the generic relay class.

**Pull request closed without merging**
