### PR TITLE
Pull adc121c021

### PR DESCRIPTION
**Pull request by Jon-ICS**
This driver adds support for the Grove I2C ADC module based on the adc121c021.

### CODE REVIEW

**Comment by sknepper** [comment]
I polished and pushed.  My local build worked fine, but the continuous integration testing failed, so I'm not going to close this just yet.
Also, any reason for the differences between the C++ and JavaScript examples (the JS one finds the average over 30 values; the C++ one doesn't)?

**Comment by Jon-ICS** [comment]
Ok, is there anyway to see the CI results?

At anyrate, there is no need for the 30-round averaging in the JS example, I'll ask Zion about it.

**Comment by sknepper** [comment]
The CI system was using an older build of MRAA, so this PR can be closed.  Thanks!

**Comment by Jon-ICS** [comment]
On 01/13/2015 11:49 AM, sknepper wrote:
>
> The CI system was using an older build of MRAA, so this PR can be 
> closed. Thanks!
>

Do we still need to fix the JS example?

> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/intel-iot-devkit/upm/pull/41#issuecomment-69796799>.
>

-- 
Jon Trulson
Integrated Computer Solutions
www.ics.com

**Comment by sknepper** [comment]
I don't have the sensor so I can't test it to see if the averaging is or is not necessary.  It's appreciated to have consistency between the examples in various languages (C++, JavaScript, and/or Python).  So if you and/or Zion are able to test and make changes to an example and submit another pull request, that's great!  But if you guys are busy with new sensor library development, then that work may be of higher priority than consistency between examples.  Thanks!

**Comment by Jon-ICS** [comment]
On 01/13/2015 11:59 AM, sknepper wrote:
>
> I don't have the sensor so I can't test it to see if the averaging is 
> or is not necessary. It's appreciated to have consistency between the 
> examples in various languages (C++, JavaScript, and/or Python). So if 
> you and/or Zion are able to test and make changes to an example and 
> submit another pull request, that's great! But if you guys are busy 
> with new sensor library development, then that work may be of higher 
> priority than consistency between examples. Thanks!
>

Ok, Zion will redo that one and we will issue a new PR for it in the 
future.  The loop won't hurt, but is not necessary.

-- 
Jon Trulson
Integrated Computer Solutions
www.ics.com

**Pull request closed without merging**
