### PR TITLE
ppd42ns: convert pcs/0.01cf to μg/m3 to aqi

### PR DESCRIPTION
**Pull request by chihchun**
The current implementation does not use the correction factors based
on the presence of humidity and rain.

### CODE REVIEW

**Comment by Propanu** [comment]
Hi, can you please amend your commit and sign it (you can use something like `git commit --amend -s --no-edit`. Also, I wouldn't mind at all if you wanted to add your name to the authors list. Thanks!

**Comment by Propanu** [comment]
@chihchun I won't be able to merge these changes until you sign-off your commit.

**Comment by SunHaoli** [comment]
@chihchun Hi, Rex. You commented that humidity is required to calculate accurate PM value, but I can't find any research or material about this. Would you please share some information about that? Thanks.

**Comment by SunHaoli** [comment]
@chihchun And Why do you define the radius of PM particle 0.44 um instead of 1.25 um?
And what material did you based on to determine the density of pm particles?

**Comment by coold8d** [comment]
Hi all,
I am looking for something like this conversion for my ppd42ns. 
I know it's just an estimation, but has anyone tested with this code yet?


Conversion to mass concentration was perform under strong assumption:
• All particles are spherical, with a density of 1.65E12 μg/m3
[*,**]
• The radius of a particle in the channel <2.5 μm is 0.44 μm [**,***]
• The radius of a particle in the channel > 2.5 is 2.60 μm [**,***]

**Comment by Lucianovici** [comment]
Hi guys,

Any progress on this? I just stumble upon this PR trying to find a way to convert pcs/0.01cf to ug/m3.

There are some experiments that are encouraging to NOT use ppd42ns for AQI calculation.

"calculating the AQI from a Shinyei sensor could prove to be very arbitrary"
http://aqicn.org/sensor/shinyei/

Any thoughts?

**Comment by Propanu** [comment]
Hi, the original poster never signed-off on this code hence why it wasn't merged. Also, the accuracy of the conversions hasn't been tested.

However, if this functionality is useful we can do a code review and add it. Personally, I would even split the AQI calculation and include it as part of the UPM utilities class since the similar [HKA5](../tree/master/src/hka5) sensor module also returns ug/m3.

**Comment by Lucianovici** [comment]
It could be that the sensor from [dfrobot](https://www.dfrobot.com/wiki/index.php/PM2.5_laser_dust_sensor_SKU:SEN0177) is more accurate. Thanks for the tips @Propanu 

An interesting (and maybe cheaper) alternative here: https://www.hackster.io/edwios/air-quality-monitor-3f422f

**Comment by malikabhi05** [comment]
Since the author @chihchun didn't respond to the thread and add a signoff to his commit, the code from this commit was added to UPM as a part of another commit (7a60cd5abebd0fceca8009d3a15fcae3a62e1d93), @chihchun was added as a contributor in all the files affected. The  pcs2ugm3 function was added to the ppd42ns.c file and the AQI calculation function-"upm_ugm3_to_aqi" was added to the upm utilities. This PR was based on the this  [https://www.yumpu.com/en/document/view/31692906/preliminary-screening-system-for-ambient-air-quality-in-southeast-](paper).

The functions were tested and seemed to work fine, in case any changes are required they can be requested/made to the individual functions moving forward. I will keep the PR open for a few more days before closing, if anyone on this thread has any concerns then please leave a comment.

**Comment by malikabhi05** [comment]
Implemented. Closing this PR.

**Pull request closed without merging**
