### PR TITLE
Itg3200 py

### PR DESCRIPTION
**Pull request by jrvandr**
Python sample along with swig python pointer changes

### CODE REVIEW

**Comment by Propanu** [comment]
Can you please do a quick rebase and squash these into a single commit?

**Comment by sknepper** [comment]
Actually, I think it's better to keep them separated.

**Comment by sknepper** [comment]
One of the commits has to do with fixing the Python bindings, the other is a new example.  For previous PRs like this (with a new example and also a fix for the bindings), we've been separating them into multiple commits.  Only when the entire sensor library is new have we been squashing commits into just one commit.

**Comment by jrvandr** [comment]
merged and closing

**Pull request closed without merging**
