### PR TITLE
Changed Node.js Modules from jsupm_grove & Removed 'Grove' from Comments. Fixes #480.

### LINKED ISSUE #480: Some Grove-independent JS examples still using jsupm_grove
I see that there are separate JS snippets for Grove sensors and otherwise. However, looks like some of the non-Grove examples also seem to be using `jsupm_grove` instead of `jsupm_<sensor>`, which means that when the sensors are being initialised (as JS objects), an incorrect constructor is being called. I've gone through some of the files really quickly and found that this mistake exists in:

- [Grove Button](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/grovebutton.js) vs. [Button](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/button.js)
- [Grove Rotary](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/groverotary.js) vs. [Rotary](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/rotary.js)
- [Grove Relay](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/groverelay.js) vs. [Relay](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/relay.js)

I'll build the above list if I find any more. I can also submit a PR fixing the issue if you wish.

On a side note, some of the correct usages can be found in:

- [Grove LED](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/groveled.js) vs. [LED](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/led.js)
- [Grove Temp](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/grovetemp.js) vs. [Temp](https://github.com/intel-iot-devkit/upm/blob/master/examples/javascript/temperature.js)

Closes #474.

### PR DESCRIPTION
**Pull request by SuyashLakhotia**
Fixes #480

### CODE REVIEW

**Comment by Propanu** [comment]
Hi, thanks for finding and submitting these. I'll have to ask for a sign-off on the commits though before they can be merged.

**Comment by SuyashLakhotia** [comment]
@Propanu Done...I think. Is `git commit --signoff` what you meant?

**Comment by Propanu** [comment]
Yes! Thanks a lot, I'll handle it from here.

**Comment by Propanu** [comment]
Merged as of 1aa748e3d6042b44bdb294a3e6f0543131967a92. Thanks again!

**Pull request closed without merging**
