### PR TITLE
upgrade files smartdrive.cxx and smartdrive.hpp, after several tests have been done in 5/19/2017, by Neuber José de Sousa <neuberfran@gmail.com> 

### PR DESCRIPTION
**Pull request by neuberfran**
**I do this:**

> Commit message needs to be updated, I used "x" and "y" as placeholders for actual description of changes.
> 
> Author should not be removed and replaced, it's fine if you want to add yourself to the list though.
> 
> There are a couple of instances where you replace a symbol with the exact same numerical value in the .hpp file, e.g. CMD_S == 0x53. This is not needed.
> 
> In some places you use a hard-coded '5' when calling writeArray(), but the array is larger than 5 bytes, throwing away the rest of the command.
> 
> You shouldn't make repeated calls to i2c.address since it's saved in the context (see #547).
> 
> Formatting/indentation should match existing code (you have extra spaces, tabs, etc.)

**and now I do new PR**

### CODE REVIEW

**Comment by neuberfran** [comment]
according to this: https://github.com/intel-iot-devkit/upm/pull/554

I do  rm –rf /usr/local/lib
And rm –rf /usr/lib
opkg update
opkg upgrade mraa upm

**and not solved**

Please accept this PR and change files smartdrive.cxx and smartdrive.hpp of the upm sensor driver

**Comment by neuberfran** [comment]
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
examples/java/CMakeLists.txt
src/lis2ds12/lis2ds12.hpp

**Comment by neuberfran** [comment]
Why the smartdrive.cxx and smartdrive.hpp files have not yet been changed?

https://github.com/intel-iot-devkit/upm/pull/565

**Comment by neuberfran** [comment]
Driver funcionou no Android Things DP3 / intel edison / jcenter / gradle

**Comment by neuberfran** [comment]
Driver funcionou no Android Things DP3 / intel edison / jcenter / gradle

**Comment by pylbert** [comment]
If #556 and #557 are PRs aimed at making the same change, can we remove one and update whichever one is needed?

**Comment by neuberfran** [comment]
Yes

**Comment by neuberfran** [comment]
Yes

**Comment by neuberfran** [comment]
Ok

**Pull request closed without merging**
